author: wizzledonker
api-version: '1.21'
database: false
description: Telepads allows players to setup a network of teleport pads which are
  connected to each other, and teleport when stood upon.
main: me.wizzledonker.plugins.telepads.Telepads
name: TelePads
load: POSTWORLD
version: '2.0'
commands:
  createpad:
    description: Creates a teleport pad with the specified name
    usage: /<command> <name>
    aliases: [padcreate, namepad, newpad, setpad]
  padlink:
    description: Links two pads together for teleportation
    usage: /<command> <pad1> <pad2>
    aliases: [linkpads, tellink, pad2pad]
  padunlink:
    description: Unlinks a pad and sets it to go nowhere
    usage: /<command> <pad>
    aliases: [unlinkpads, onewaypad]
  delpad:
    description: Deletes a teleport pad from the config and reloads the config file.
    usage: /<command> <pad>
    aliases: [paddel, destroypad, deletepad]
  linkpadhere:
    description: Link a teleport pad to your current location.
    usage: /<command> <pad>
    aliases: [lph, linkpad2p, padtome]
  padlist:
    description: List all the available pads for teleportation
    usage: /<command>
    aliases: [listpad, listpads, pads, telepads]
permissions:
  telepads.list:
    description: Defines whether a player can view the pad list
    default: op
  telepads.create:
    description: Defines whether or not a player can create a teleport pad
    default: op
  telepads.delete:
    description: Defines whether a player can delete a teleport pad
    default: op
  telepads.use:
    description: Defines if players may use TelePads
    default: true
  telepads.link:
    description: Players with this permission can link telepads
    default: op
  telepads.linkhere:
    description: Players with this permission can link pads to their location
    default: op
  telepads.unlink:
    description: Players with this permission can unlink a telepad
    default: op
  telepads.pads:
    description: Grants access to all telepads
    default: true
